version : '3'
services:
  postgres:
    image: 'postgres'
    restart: always
  redis:
    image: 'redis:2.8.0'
    restart: always
  nginx:
    restart: always
    build: 
      dockerfile: dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    restart: always
    build:
      dockerfile: dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=3679
      - PGUSER=postgres
      - PGHOST=postgres                                                         - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    restart: always
    build:
      dockerfile: dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    restart: always
    build:
      dockerfile: dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app